import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";  // Import global CSS here
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="container">
            <a className="flex title-font items-center">
              <div className="avatar">
                <Image
                  src="/me1.jpg"
                  alt="logo"
                  width={80}
                  height={80}
                  className="avatar-img"
                />
              </div>
              <h1>Portfolio</h1>
            </a>
            <nav>
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/skills">Skills</Link>
              <Link href="/projects">Projects</Link>
              <Link href="/services">Services</Link>
              <Link href="/contact">Contact</Link>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
